# Site settings
url: ""
baseurl: ""
title: Sumesh John
email: sm2john@uwaterloo.ca
description: "Come see what I've worked on!"

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor